# Generated by Django 5.1 on 2024-08-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShipmentRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("shipment_mode", models.CharField(max_length=255)),
                ("fulfillment_method", models.CharField(max_length=255)),
                ("molecule_or_test_type", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=255)),
                ("dosage_form", models.CharField(max_length=255)),
                ("manufacturing_site", models.CharField(max_length=255)),
                ("irst_line_designation", models.CharField(max_length=255)),
                ("weight_kg", models.CharField(max_length=255)),
                ("freight_cost_usd", models.CharField(max_length=255)),
                ("line_item_insurance_usd", models.CharField(max_length=255)),
                ("vendor", models.CharField(max_length=255)),
                ("first_line_designation", models.CharField(max_length=255)),
                ("unit_per_pack", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "line_item_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "line_item_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("pack_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("scheduled_delivery_date", models.DateField()),
                ("delivered_to_client_date", models.DateField()),
            ],
        ),
    ]
