# Generated by Django 5.1 on 2024-08-14 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipmentroute",
            name="id",
        ),
    ]
