# Generated by Django 5.1 on 2024-08-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_remove_shipmentroute_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentroute",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
