# Generated by Django 5.1 on 2024-08-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_shipmentroute_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentroute",
            name="code",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
